### ISSUE TITLE
ReLSO - BaseVAEParamModule 

### ISSUE THREAD

**Issue by pgatoula** [KrishnaswamyLab/ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers#7]
Hello,
I am honestly apologize for the inconvenience.
We would like to thank you for your work and this amazing repo !
I would like to ask you if ReLSO has been/ could be implemented as BaseVAEParamModule because now it is based on BaseModel ?
In that case interpolation sampling is suggested to be used before or after the reparametrization trick ?
Any information would be helpful,
Thank you in advance for your time and for your work !!!

**Comment by ec1340** [comment]
Hello. Thanks for your question!

In the provided implementation, the `relso1` model inherits from the `BaseModel` class as you've noticed which follows a normal autoencoder approach. To change ReLSO into a VAE, it would take some minor changes - adjusting the encoder to instead produce two output tensors from the encoder for `mu` and the `logvar` inputs expected by reparameterization step. 

You can use the two networks `mu_layer` and `var_layer` provided in `BaseVAEParamModule` to do this.

A possible implementation (but definitely not the only way) would be to change the [relso.encode ](https://github.com/KrishnaswamyLab/ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers/blob/f2fee841da406bb38f080af4445b5f790af31c43/relso/nn/models.py#L182) function like so,


    #VAE version
    def encode(self, batch):
        embedded_batch = self.embed(batch)
        output_embed = self.transformer_encoding(embedded_batch)

        glob_attn = self.glob_attn_module(output_embed)  # output should be B x S x 1
        z_rep = torch.bmm(glob_attn.transpose(-1, 1), output_embed).squeeze()

        # to regain the batch dimension
        if len(embedded_batch) == 1:
            z_rep = z_rep.unsqueeze(0)

        z_rep = self.bottleneck_module(z_rep)
        
        # new
        mu = self.mu_layer(z_rep)
        logvar = self.var_layer(z_rep) 
        z_rep = self.reparameterize(mu, logvar)
        
        return z_rep


As mentioned, you can get the networks from [here](https://github.com/KrishnaswamyLab/ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers/blob/f2fee841da406bb38f080af4445b5f790af31c43/relso/nn/base.py#L175) and the reparameterize function from [here](https://github.com/KrishnaswamyLab/ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers/blob/f2fee841da406bb38f080af4445b5f790af31c43/relso/nn/base.py#L108)

**Comment by pgatoula** [comment]
Thank you very much for your immediate response!
